# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddStockDialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_AddStockDialog(object):
    def setupUi(self, AddStockDialog):
        AddStockDialog.setObjectName("AddStockDialog")
        AddStockDialog.resize(266, 195)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AddStockDialog.sizePolicy().hasHeightForWidth())
        AddStockDialog.setSizePolicy(sizePolicy)
        AddStockDialog.setInputMethodHints(QtCore.Qt.ImhNone)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(AddStockDialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEditTicker = QtWidgets.QLineEdit(AddStockDialog)
        self.lineEditTicker.setObjectName("lineEditTicker")
        self.verticalLayout_3.addWidget(self.lineEditTicker)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButtonWatchList = QtWidgets.QRadioButton(AddStockDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButtonWatchList.sizePolicy().hasHeightForWidth())
        self.radioButtonWatchList.setSizePolicy(sizePolicy)
        self.radioButtonWatchList.setChecked(True)
        self.radioButtonWatchList.setObjectName("radioButtonWatchList")
        self.verticalLayout_2.addWidget(self.radioButtonWatchList, 0, QtCore.Qt.AlignTop)
        self.labelShares = QtWidgets.QLabel(AddStockDialog)
        self.labelShares.setObjectName("labelShares")
        self.verticalLayout_2.addWidget(self.labelShares, 0, QtCore.Qt.AlignTop)
        self.lineEditShares = QtWidgets.QLineEdit(AddStockDialog)
        self.lineEditShares.setReadOnly(True)
        self.lineEditShares.setObjectName("lineEditShares")
        self.verticalLayout_2.addWidget(self.lineEditShares, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButtonPortfolio = QtWidgets.QRadioButton(AddStockDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButtonPortfolio.sizePolicy().hasHeightForWidth())
        self.radioButtonPortfolio.setSizePolicy(sizePolicy)
        self.radioButtonPortfolio.setObjectName("radioButtonPortfolio")
        self.verticalLayout.addWidget(self.radioButtonPortfolio, 0, QtCore.Qt.AlignTop)
        self.labelPrices = QtWidgets.QLabel(AddStockDialog)
        self.labelPrices.setObjectName("labelPrices")
        self.verticalLayout.addWidget(self.labelPrices, 0, QtCore.Qt.AlignTop)
        self.lineEditPrices = QtWidgets.QLineEdit(AddStockDialog)
        self.lineEditPrices.setReadOnly(True)
        self.lineEditPrices.setObjectName("lineEditPrices")
        self.verticalLayout.addWidget(self.lineEditPrices, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.labelError = QtWidgets.QLabel(AddStockDialog)
        self.labelError.setObjectName("labelError")
        self.verticalLayout_3.addWidget(self.labelError, 0, QtCore.Qt.AlignTop)
        self.buttonBox = QtWidgets.QDialogButtonBox(AddStockDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox, 0, QtCore.Qt.AlignTop)

        self.retranslateUi(AddStockDialog)
        self.buttonBox.accepted.connect(AddStockDialog.accept)
        self.buttonBox.rejected.connect(AddStockDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AddStockDialog)
        AddStockDialog.setTabOrder(self.lineEditTicker, self.radioButtonWatchList)
        AddStockDialog.setTabOrder(self.radioButtonWatchList, self.radioButtonPortfolio)
        AddStockDialog.setTabOrder(self.radioButtonPortfolio, self.lineEditShares)
        AddStockDialog.setTabOrder(self.lineEditShares, self.lineEditPrices)

    def retranslateUi(self, AddStockDialog):
        _translate = QtCore.QCoreApplication.translate
        AddStockDialog.setWindowTitle(_translate("AddStockDialog", "Add Stock"))
        self.lineEditTicker.setPlaceholderText(_translate("AddStockDialog", "TICKER"))
        self.radioButtonWatchList.setText(_translate("AddStockDialog", "Watch List"))
        self.labelShares.setText(_translate("AddStockDialog", "Share(s):"))
        self.lineEditShares.setPlaceholderText(_translate("AddStockDialog", "200, 140"))
        self.radioButtonPortfolio.setText(_translate("AddStockDialog", "Portfolio"))
        self.labelPrices.setText(_translate("AddStockDialog", "Price(s):"))
        self.lineEditPrices.setPlaceholderText(_translate("AddStockDialog", "23.33, 24.33"))
        self.labelError.setText(_translate("AddStockDialog", "<html><head/><body><p><span style=\" color:#ff0000;\">Error: Invalid Ticker</span></p></body></html>"))

