# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ExpressionCreatorDialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_ExpressionCreatorDialog(object):
    def setupUi(self, ExpressionCreatorDialog):
        ExpressionCreatorDialog.setObjectName("ExpressionCreatorDialog")
        ExpressionCreatorDialog.resize(542, 734)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(ExpressionCreatorDialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelVariables = QtWidgets.QLabel(ExpressionCreatorDialog)
        self.labelVariables.setObjectName("labelVariables")
        self.verticalLayout_2.addWidget(self.labelVariables)
        self.listViewVariableBox = QtWidgets.QListWidget(ExpressionCreatorDialog)
        self.listViewVariableBox.setObjectName("listViewVariableBox")
        self.verticalLayout_2.addWidget(self.listViewVariableBox)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelOperators = QtWidgets.QLabel(ExpressionCreatorDialog)
        self.labelOperators.setObjectName("labelOperators")
        self.verticalLayout.addWidget(self.labelOperators)
        self.listViewOperatorBox = QtWidgets.QListWidget(ExpressionCreatorDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listViewOperatorBox.sizePolicy().hasHeightForWidth())
        self.listViewOperatorBox.setSizePolicy(sizePolicy)
        self.listViewOperatorBox.setObjectName("listViewOperatorBox")
        self.verticalLayout.addWidget(self.listViewOperatorBox)
        self.labelConditionalOperators = QtWidgets.QLabel(ExpressionCreatorDialog)
        self.labelConditionalOperators.setObjectName("labelConditionalOperators")
        self.verticalLayout.addWidget(self.labelConditionalOperators)
        self.listViewConditionalBox = QtWidgets.QListWidget(ExpressionCreatorDialog)
        self.listViewConditionalBox.setObjectName("listViewConditionalBox")
        self.verticalLayout.addWidget(self.listViewConditionalBox)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.labelSelectedVariableDescription = QtWidgets.QLabel(ExpressionCreatorDialog)
        self.labelSelectedVariableDescription.setObjectName("labelSelectedVariableDescription")
        self.verticalLayout_3.addWidget(self.labelSelectedVariableDescription)
        self.layoutExpression = QtWidgets.QVBoxLayout()
        self.layoutExpression.setObjectName("layoutExpression")
        self.labelExpression = QtWidgets.QLabel(ExpressionCreatorDialog)
        self.labelExpression.setObjectName("labelExpression")
        self.layoutExpression.addWidget(self.labelExpression)
        self.lineEditExpression = QtWidgets.QLineEdit(ExpressionCreatorDialog)
        self.lineEditExpression.setText("")
        self.lineEditExpression.setObjectName("lineEditExpression")
        self.layoutExpression.addWidget(self.lineEditExpression)
        self.verticalLayout_3.addLayout(self.layoutExpression)
        self.labelErrorExpression = QtWidgets.QLabel(ExpressionCreatorDialog)
        self.labelErrorExpression.setObjectName("labelErrorExpression")
        self.verticalLayout_3.addWidget(self.labelErrorExpression)
        self.layoutCheckboxes = QtWidgets.QHBoxLayout()
        self.layoutCheckboxes.setObjectName("layoutCheckboxes")
        self.checkBoxAddToHeaders = QtWidgets.QCheckBox(ExpressionCreatorDialog)
        self.checkBoxAddToHeaders.setObjectName("checkBoxAddToHeaders")
        self.layoutCheckboxes.addWidget(self.checkBoxAddToHeaders)
        self.checkBoxSaveVariable = QtWidgets.QCheckBox(ExpressionCreatorDialog)
        self.checkBoxSaveVariable.setObjectName("checkBoxSaveVariable")
        self.layoutCheckboxes.addWidget(self.checkBoxSaveVariable)
        self.verticalLayout_3.addLayout(self.layoutCheckboxes)
        self.layoutHeader = QtWidgets.QVBoxLayout()
        self.layoutHeader.setObjectName("layoutHeader")
        self.labelHeaderName = QtWidgets.QLabel(ExpressionCreatorDialog)
        self.labelHeaderName.setObjectName("labelHeaderName")
        self.layoutHeader.addWidget(self.labelHeaderName)
        self.lineEditHeaderName = QtWidgets.QLineEdit(ExpressionCreatorDialog)
        self.lineEditHeaderName.setText("")
        self.lineEditHeaderName.setObjectName("lineEditHeaderName")
        self.layoutHeader.addWidget(self.lineEditHeaderName)
        self.labelErrorHeader = QtWidgets.QLabel(ExpressionCreatorDialog)
        self.labelErrorHeader.setObjectName("labelErrorHeader")
        self.layoutHeader.addWidget(self.labelErrorHeader)
        self.verticalLayout_3.addLayout(self.layoutHeader)
        self.layoutConditional = QtWidgets.QVBoxLayout()
        self.layoutConditional.setObjectName("layoutConditional")
        self.checkBoxAddConditional = QtWidgets.QCheckBox(ExpressionCreatorDialog)
        self.checkBoxAddConditional.setObjectName("checkBoxAddConditional")
        self.layoutConditional.addWidget(self.checkBoxAddConditional)
        self.labelConditional = QtWidgets.QLabel(ExpressionCreatorDialog)
        self.labelConditional.setObjectName("labelConditional")
        self.layoutConditional.addWidget(self.labelConditional)
        self.lineEditConditional = QtWidgets.QLineEdit(ExpressionCreatorDialog)
        self.lineEditConditional.setText("")
        self.lineEditConditional.setObjectName("lineEditConditional")
        self.layoutConditional.addWidget(self.lineEditConditional)
        self.labelErrorConditional = QtWidgets.QLabel(ExpressionCreatorDialog)
        self.labelErrorConditional.setObjectName("labelErrorConditional")
        self.layoutConditional.addWidget(self.labelErrorConditional)
        self.verticalLayout_3.addLayout(self.layoutConditional)
        self.layoutCustomVariables = QtWidgets.QVBoxLayout()
        self.layoutCustomVariables.setObjectName("layoutCustomVariables")
        self.layoutNameSubCustomVariables = QtWidgets.QVBoxLayout()
        self.layoutNameSubCustomVariables.setObjectName("layoutNameSubCustomVariables")
        self.labelCustomVariable = QtWidgets.QLabel(ExpressionCreatorDialog)
        self.labelCustomVariable.setObjectName("labelCustomVariable")
        self.layoutNameSubCustomVariables.addWidget(self.labelCustomVariable)
        self.lineEditCustomVariableName = QtWidgets.QLineEdit(ExpressionCreatorDialog)
        self.lineEditCustomVariableName.setObjectName("lineEditCustomVariableName")
        self.layoutNameSubCustomVariables.addWidget(self.lineEditCustomVariableName)
        self.layoutCustomVariables.addLayout(self.layoutNameSubCustomVariables)
        self.labelErrorVariableName = QtWidgets.QLabel(ExpressionCreatorDialog)
        self.labelErrorVariableName.setObjectName("labelErrorVariableName")
        self.layoutCustomVariables.addWidget(self.labelErrorVariableName)
        self.layoutDescriptionSubCustomVariables = QtWidgets.QVBoxLayout()
        self.layoutDescriptionSubCustomVariables.setObjectName("layoutDescriptionSubCustomVariables")
        self.labelDescription = QtWidgets.QLabel(ExpressionCreatorDialog)
        self.labelDescription.setObjectName("labelDescription")
        self.layoutDescriptionSubCustomVariables.addWidget(self.labelDescription)
        self.lineEditVariableDescription = QtWidgets.QLineEdit(ExpressionCreatorDialog)
        self.lineEditVariableDescription.setObjectName("lineEditVariableDescription")
        self.layoutDescriptionSubCustomVariables.addWidget(self.lineEditVariableDescription)
        self.layoutCustomVariables.addLayout(self.layoutDescriptionSubCustomVariables)
        self.verticalLayout_3.addLayout(self.layoutCustomVariables)
        self.buttonBox = QtWidgets.QDialogButtonBox(ExpressionCreatorDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(ExpressionCreatorDialog)
        self.buttonBox.accepted.connect(ExpressionCreatorDialog.accept)
        self.buttonBox.rejected.connect(ExpressionCreatorDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ExpressionCreatorDialog)

    def retranslateUi(self, ExpressionCreatorDialog):
        _translate = QtCore.QCoreApplication.translate
        ExpressionCreatorDialog.setWindowTitle(_translate("ExpressionCreatorDialog", "Expression Creator"))
        self.labelVariables.setText(_translate("ExpressionCreatorDialog", "Variables:"))
        self.listViewVariableBox.setSortingEnabled(True)
        self.labelOperators.setText(_translate("ExpressionCreatorDialog", "Operators:"))
        self.listViewOperatorBox.setSortingEnabled(False)
        self.labelConditionalOperators.setText(_translate("ExpressionCreatorDialog", "Conditional Operators"))
        self.listViewConditionalBox.setSortingEnabled(False)
        self.labelSelectedVariableDescription.setText(_translate("ExpressionCreatorDialog", "Variable Description..."))
        self.labelExpression.setText(_translate("ExpressionCreatorDialog", "Expression:"))
        self.lineEditExpression.setPlaceholderText(_translate("ExpressionCreatorDialog", "volume * 4 / 10"))
        self.labelErrorExpression.setText(_translate("ExpressionCreatorDialog", "<html><head/><body><p><span style=\" color:#ff0000;\">Error</span></p></body></html>"))
        self.checkBoxAddToHeaders.setText(_translate("ExpressionCreatorDialog", "Add to Headers"))
        self.checkBoxSaveVariable.setText(_translate("ExpressionCreatorDialog", "Save as Custom Variable"))
        self.labelHeaderName.setText(_translate("ExpressionCreatorDialog", "Header Name:"))
        self.lineEditHeaderName.setPlaceholderText(_translate("ExpressionCreatorDialog", "Custom Volume"))
        self.labelErrorHeader.setText(_translate("ExpressionCreatorDialog", "<html><head/><body><p><span style=\" color:#ff0000;\">Error</span></p></body></html>"))
        self.checkBoxAddConditional.setText(_translate("ExpressionCreatorDialog", "Add Conditional"))
        self.labelConditional.setText(_translate("ExpressionCreatorDialog", "Conditional:"))
        self.lineEditConditional.setPlaceholderText(_translate("ExpressionCreatorDialog", "if volume > 100 then Color.Red"))
        self.labelErrorConditional.setText(_translate("ExpressionCreatorDialog", "<html><head/><body><p><span style=\" color:#ff0000;\">Error</span></p></body></html>"))
        self.labelCustomVariable.setText(_translate("ExpressionCreatorDialog", "Custom Variable Name"))
        self.lineEditCustomVariableName.setPlaceholderText(_translate("ExpressionCreatorDialog", "newVariable"))
        self.labelErrorVariableName.setText(_translate("ExpressionCreatorDialog", "<html><head/><body><p><span style=\" color:#ff0000;\">Error</span></p></body></html>"))
        self.labelDescription.setText(_translate("ExpressionCreatorDialog", "Description:"))
        self.lineEditVariableDescription.setPlaceholderText(_translate("ExpressionCreatorDialog", "volume multiplied by 4 and divided by 10"))

