# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ExpressionCreatorDialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_ExpressionCreatorDialog(object):
    def setupUi(self, ExpressionCreatorDialog):
        ExpressionCreatorDialog.setObjectName("ExpressionCreatorDialog")
        ExpressionCreatorDialog.resize(538, 678)
        self.verticalLayout = QtWidgets.QVBoxLayout(ExpressionCreatorDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layoutListboxLabels = QtWidgets.QHBoxLayout()
        self.layoutListboxLabels.setObjectName("layoutListboxLabels")
        self.labelVariables = QtWidgets.QLabel(ExpressionCreatorDialog)
        self.labelVariables.setObjectName("labelVariables")
        self.layoutListboxLabels.addWidget(self.labelVariables)
        self.labelOperators = QtWidgets.QLabel(ExpressionCreatorDialog)
        self.labelOperators.setObjectName("labelOperators")
        self.layoutListboxLabels.addWidget(self.labelOperators)
        self.verticalLayout.addLayout(self.layoutListboxLabels)
        self.layoutListboxes = QtWidgets.QHBoxLayout()
        self.layoutListboxes.setObjectName("layoutListboxes")
        self.listViewVariableBox = QtWidgets.QListWidget(ExpressionCreatorDialog)
        self.listViewVariableBox.setObjectName("listViewVariableBox")
        self.layoutListboxes.addWidget(self.listViewVariableBox)
        self.listViewOperatorBox = QtWidgets.QListWidget(ExpressionCreatorDialog)
        self.listViewOperatorBox.setObjectName("listViewOperatorBox")
        self.layoutListboxes.addWidget(self.listViewOperatorBox)
        self.verticalLayout.addLayout(self.layoutListboxes)
        self.labelSelectedVariableDescription = QtWidgets.QLabel(ExpressionCreatorDialog)
        self.labelSelectedVariableDescription.setObjectName("labelSelectedVariableDescription")
        self.verticalLayout.addWidget(self.labelSelectedVariableDescription)
        self.layoutExpression = QtWidgets.QVBoxLayout()
        self.layoutExpression.setObjectName("layoutExpression")
        self.labelExpression = QtWidgets.QLabel(ExpressionCreatorDialog)
        self.labelExpression.setObjectName("labelExpression")
        self.layoutExpression.addWidget(self.labelExpression)
        self.lineEditExpression = QtWidgets.QLineEdit(ExpressionCreatorDialog)
        self.lineEditExpression.setText("")
        self.lineEditExpression.setObjectName("lineEditExpression")
        self.layoutExpression.addWidget(self.lineEditExpression)
        self.verticalLayout.addLayout(self.layoutExpression)
        self.layoutCheckboxes = QtWidgets.QHBoxLayout()
        self.layoutCheckboxes.setObjectName("layoutCheckboxes")
        self.checkBoxAddToHeaders = QtWidgets.QCheckBox(ExpressionCreatorDialog)
        self.checkBoxAddToHeaders.setObjectName("checkBoxAddToHeaders")
        self.layoutCheckboxes.addWidget(self.checkBoxAddToHeaders)
        self.checkBoxSaveVariable = QtWidgets.QCheckBox(ExpressionCreatorDialog)
        self.checkBoxSaveVariable.setObjectName("checkBoxSaveVariable")
        self.layoutCheckboxes.addWidget(self.checkBoxSaveVariable)
        self.verticalLayout.addLayout(self.layoutCheckboxes)
        self.layoutHeader = QtWidgets.QVBoxLayout()
        self.layoutHeader.setObjectName("layoutHeader")
        self.labelHeaderName = QtWidgets.QLabel(ExpressionCreatorDialog)
        self.labelHeaderName.setObjectName("labelHeaderName")
        self.layoutHeader.addWidget(self.labelHeaderName)
        self.llineEditHeaderName = QtWidgets.QLineEdit(ExpressionCreatorDialog)
        self.llineEditHeaderName.setText("")
        self.llineEditHeaderName.setObjectName("llineEditHeaderName")
        self.layoutHeader.addWidget(self.llineEditHeaderName)
        self.checkBoxAddConditional = QtWidgets.QCheckBox(ExpressionCreatorDialog)
        self.checkBoxAddConditional.setObjectName("checkBoxAddConditional")
        self.layoutHeader.addWidget(self.checkBoxAddConditional)
        self.verticalLayout.addLayout(self.layoutHeader)
        self.layoutConditional = QtWidgets.QVBoxLayout()
        self.layoutConditional.setObjectName("layoutConditional")
        self.labelConditional = QtWidgets.QLabel(ExpressionCreatorDialog)
        self.labelConditional.setObjectName("labelConditional")
        self.layoutConditional.addWidget(self.labelConditional)
        self.lineEditConditional = QtWidgets.QLineEdit(ExpressionCreatorDialog)
        self.lineEditConditional.setText("")
        self.lineEditConditional.setObjectName("lineEditConditional")
        self.layoutConditional.addWidget(self.lineEditConditional)
        self.verticalLayout.addLayout(self.layoutConditional)
        self.layoutCustomVariables = QtWidgets.QVBoxLayout()
        self.layoutCustomVariables.setObjectName("layoutCustomVariables")
        self.layoutNameSubCustomVariables = QtWidgets.QVBoxLayout()
        self.layoutNameSubCustomVariables.setObjectName("layoutNameSubCustomVariables")
        self.labelCustomVariable = QtWidgets.QLabel(ExpressionCreatorDialog)
        self.labelCustomVariable.setObjectName("labelCustomVariable")
        self.layoutNameSubCustomVariables.addWidget(self.labelCustomVariable)
        self.lineEditCustomVariableName = QtWidgets.QLineEdit(ExpressionCreatorDialog)
        self.lineEditCustomVariableName.setObjectName("lineEditCustomVariableName")
        self.layoutNameSubCustomVariables.addWidget(self.lineEditCustomVariableName)
        self.layoutCustomVariables.addLayout(self.layoutNameSubCustomVariables)
        self.layoutDescriptionSubCustomVariables = QtWidgets.QVBoxLayout()
        self.layoutDescriptionSubCustomVariables.setObjectName("layoutDescriptionSubCustomVariables")
        self.labelDescription = QtWidgets.QLabel(ExpressionCreatorDialog)
        self.labelDescription.setObjectName("labelDescription")
        self.layoutDescriptionSubCustomVariables.addWidget(self.labelDescription)
        self.lineEditVariableDescription = QtWidgets.QLineEdit(ExpressionCreatorDialog)
        self.lineEditVariableDescription.setObjectName("lineEditVariableDescription")
        self.layoutDescriptionSubCustomVariables.addWidget(self.lineEditVariableDescription)
        self.layoutCustomVariables.addLayout(self.layoutDescriptionSubCustomVariables)
        self.verticalLayout.addLayout(self.layoutCustomVariables)
        self.labelError = QtWidgets.QLabel(ExpressionCreatorDialog)
        self.labelError.setObjectName("labelError")
        self.verticalLayout.addWidget(self.labelError)
        self.buttonBox = QtWidgets.QDialogButtonBox(ExpressionCreatorDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ExpressionCreatorDialog)
        self.buttonBox.accepted.connect(ExpressionCreatorDialog.accept)
        self.buttonBox.rejected.connect(ExpressionCreatorDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ExpressionCreatorDialog)

    def retranslateUi(self, ExpressionCreatorDialog):
        _translate = QtCore.QCoreApplication.translate
        ExpressionCreatorDialog.setWindowTitle(_translate("ExpressionCreatorDialog", "Expression Creator"))
        self.labelVariables.setText(_translate("ExpressionCreatorDialog", "Variables:"))
        self.labelOperators.setText(_translate("ExpressionCreatorDialog", "Operators:"))
        self.labelSelectedVariableDescription.setText(_translate("ExpressionCreatorDialog", "Variable Description..."))
        self.labelExpression.setText(_translate("ExpressionCreatorDialog", "Expression:"))
        self.lineEditExpression.setPlaceholderText(_translate("ExpressionCreatorDialog", "volume * 4 / 10"))
        self.checkBoxAddToHeaders.setText(_translate("ExpressionCreatorDialog", "Add to Headers"))
        self.checkBoxSaveVariable.setText(_translate("ExpressionCreatorDialog", "Save as Custom Variable"))
        self.labelHeaderName.setText(_translate("ExpressionCreatorDialog", "Header Name:"))
        self.llineEditHeaderName.setPlaceholderText(_translate("ExpressionCreatorDialog", "Custom Volume"))
        self.checkBoxAddConditional.setText(_translate("ExpressionCreatorDialog", "Add Conditional"))
        self.labelConditional.setText(_translate("ExpressionCreatorDialog", "Conditional:"))
        self.lineEditConditional.setPlaceholderText(_translate("ExpressionCreatorDialog", "if $this > volume then RED"))
        self.labelCustomVariable.setText(_translate("ExpressionCreatorDialog", "Custom Variable Name"))
        self.lineEditCustomVariableName.setPlaceholderText(_translate("ExpressionCreatorDialog", "newVariable"))
        self.labelDescription.setText(_translate("ExpressionCreatorDialog", "Description:"))
        self.lineEditVariableDescription.setPlaceholderText(_translate("ExpressionCreatorDialog", "volume multiplied by 4 and divided by 10"))
        self.labelError.setText(_translate("ExpressionCreatorDialog", "<html><head/><body><p><span style=\" color:#ff0000;\">Error</span></p></body></html>"))

