# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StockViewerWidget.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_StockViewerWidget(object):
    def setupUi(self, StockViewerWidget):
        StockViewerWidget.setObjectName("StockViewerWidget")
        StockViewerWidget.resize(1038, 609)
        self.verticalLayout = QtWidgets.QVBoxLayout(StockViewerWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelTicker = QtWidgets.QLabel(StockViewerWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelTicker.setFont(font)
        self.labelTicker.setObjectName("labelTicker")
        self.horizontalLayout_2.addWidget(self.labelTicker)
        spacerItem = QtWidgets.QSpacerItem(118, 18, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButtonDrawLine = QtWidgets.QPushButton(StockViewerWidget)
        self.pushButtonDrawLine.setCheckable(True)
        self.pushButtonDrawLine.setObjectName("pushButtonDrawLine")
        self.horizontalLayout_2.addWidget(self.pushButtonDrawLine)
        self.pushButtonResize = QtWidgets.QPushButton(StockViewerWidget)
        self.pushButtonResize.setObjectName("pushButtonResize")
        self.horizontalLayout_2.addWidget(self.pushButtonResize)
        self.pushButtonReset = QtWidgets.QPushButton(StockViewerWidget)
        self.pushButtonReset.setCheckable(False)
        self.pushButtonReset.setObjectName("pushButtonReset")
        self.horizontalLayout_2.addWidget(self.pushButtonReset)
        delegate = QtWidgets.QStyledItemDelegate()
        self.comboBox = QtWidgets.QComboBox(StockViewerWidget)
        self.comboBox.setItemDelegate(delegate)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_2.addWidget(self.comboBox)
        delegate = QtWidgets.QStyledItemDelegate()
        self.comboBoxInterval = QtWidgets.QComboBox(StockViewerWidget)
        self.comboBoxInterval.setItemDelegate(delegate)
        self.comboBoxInterval.setCurrentText("")
        self.comboBoxInterval.setObjectName("comboBoxInterval")
        self.horizontalLayout_2.addWidget(self.comboBoxInterval)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget = QtWidgets.QTableWidget(StockViewerWidget)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.verticalHeader().setVisible(False)
        self.horizontalLayout.addWidget(self.tableWidget)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.graphicsView = PlotWidget(StockViewerWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout.addWidget(self.graphicsView)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.labelGraph = QtWidgets.QLabel(StockViewerWidget)
        self.labelGraph.setObjectName("labelGraph")
        self.horizontalLayout_3.addWidget(self.labelGraph)
        self.labelPosition = QtWidgets.QLabel(StockViewerWidget)
        self.labelPosition.setObjectName("labelPosition")
        self.horizontalLayout_3.addWidget(self.labelPosition)
        self.buttonBox = QtWidgets.QDialogButtonBox(StockViewerWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_3.addWidget(self.buttonBox, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(StockViewerWidget)
        self.comboBox.setCurrentIndex(-1)
        self.comboBoxInterval.setCurrentIndex(-1)
        self.buttonBox.rejected.connect(StockViewerWidget.close)
        QtCore.QMetaObject.connectSlotsByName(StockViewerWidget)

    def retranslateUi(self, StockViewerWidget):
        _translate = QtCore.QCoreApplication.translate
        StockViewerWidget.setWindowTitle(_translate("StockViewerWidget", "Form"))
        self.labelTicker.setText(_translate("StockViewerWidget", "Ticker"))
        self.pushButtonDrawLine.setText(_translate("StockViewerWidget", "Draw Line"))
        self.pushButtonResize.setText(_translate("StockViewerWidget", "Resize"))
        self.pushButtonReset.setText(_translate("StockViewerWidget", "Reset"))
        self.labelGraph.setText(_translate("StockViewerWidget", "Graph Label"))
        self.labelPosition.setText(_translate("StockViewerWidget", "Position Label"))

from pyqtgraph import PlotWidget
