# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StockViewerDialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_StockViewerDialog(object):
    def setupUi(self, StockViewerDialog):
        StockViewerDialog.setObjectName("StockViewerDialog")
        StockViewerDialog.resize(875, 527)
        self.verticalLayout = QtWidgets.QVBoxLayout(StockViewerDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelTicker = QtWidgets.QLabel(StockViewerDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelTicker.setFont(font)
        self.labelTicker.setObjectName("labelTicker")
        self.horizontalLayout_2.addWidget(self.labelTicker)
        spacerItem = QtWidgets.QSpacerItem(118, 18, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        delegate = QtWidgets.QStyledItemDelegate()
        self.comboBox = QtWidgets.QComboBox(StockViewerDialog)
        self.comboBox.setItemDelegate(delegate)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget = QtWidgets.QTableWidget(StockViewerDialog)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.verticalHeader().setVisible(False)
        self.horizontalLayout.addWidget(self.tableWidget)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.graphicsView = PlotWidget(StockViewerDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout.addWidget(self.graphicsView)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(StockViewerDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(StockViewerDialog)
        self.comboBox.setCurrentIndex(12)
        self.buttonBox.accepted.connect(StockViewerDialog.accept)
        self.buttonBox.rejected.connect(StockViewerDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(StockViewerDialog)

    def retranslateUi(self, StockViewerDialog):
        _translate = QtCore.QCoreApplication.translate
        StockViewerDialog.setWindowTitle(_translate("StockViewerDialog", "Dialog"))
        self.labelTicker.setText(_translate("StockViewerDialog", "Ticker"))
        self.comboBox.setItemText(0, _translate("StockViewerDialog", "30 minutes"))
        self.comboBox.setItemText(1, _translate("StockViewerDialog", "1 hour"))
        self.comboBox.setItemText(2, _translate("StockViewerDialog", "3 hours"))
        self.comboBox.setItemText(3, _translate("StockViewerDialog", "6 hours"))
        self.comboBox.setItemText(4, _translate("StockViewerDialog", "12 hours"))
        self.comboBox.setItemText(5, _translate("StockViewerDialog", "1 day"))
        self.comboBox.setItemText(6, _translate("StockViewerDialog", "3 days"))
        self.comboBox.setItemText(7, _translate("StockViewerDialog", "1 week"))
        self.comboBox.setItemText(8, _translate("StockViewerDialog", "2 weeks"))
        self.comboBox.setItemText(9, _translate("StockViewerDialog", "1 month"))
        self.comboBox.setItemText(10, _translate("StockViewerDialog", "3 months"))
        self.comboBox.setItemText(11, _translate("StockViewerDialog", "6 months"))
        self.comboBox.setItemText(12, _translate("StockViewerDialog", "1 year"))
        self.comboBox.setItemText(13, _translate("StockViewerDialog", "3 years"))
        self.comboBox.setItemText(14, _translate("StockViewerDialog", "5 years"))
        self.comboBox.setItemText(15, _translate("StockViewerDialog", "max"))

from pyqtgraph import PlotWidget
